name: clairvoyant
base: core24
adopt-info: clairvoyant
grade: stable
confinement: strict
contact: soumyadeepghosh2004@zohomail.in
source-code: https://github.com/cassidyjames/clairvoyant
website: https://github.com/soumyaDghosh/clairvoyant-snap
compression: lzo
platforms:
  amd64:
  arm64:
  armhf:

parts:
  clairvoyant:
    plugin: meson
    source: https://github.com/cassidyjames/clairvoyant.git
    source-tag: '3.1.7'
    source-depth: 1
    meson-parameters:
      - --prefix=/snap/clairvoyant/current/usr
    override-pull: |
      craftctl default
      sed -i 's#! Xdp.Portal.running_under_flatpak () ||##' ${CRAFT_PART_SRC}/src/MainWindow.vala
      sed -i 's|Xdp.Portal.running_under_snap|! Xdp.Portal.running_under_snap|' ${CRAFT_PART_SRC}/src/MainWindow.vala
      sed -i 's|https://cassidyjames.com/support|https://github.com/soumyaDghosh/clairvoyant-snap/issues|g' ${CRAFT_PART_SRC}/data/metainfo.appdata.xml.in
      sed -i 's|https://github.com/cassidyjames/clairvoyant/issues|https://github.com/soumyaDghosh/clairvoyant-snap/issues|g' ${CRAFT_PART_SRC}/data/metainfo.appdata.xml.in
    organize:
      snap/clairvoyant/current: .
    parse-info: [usr/share/metainfo/com.github.cassidyjames.clairvoyant.metainfo.xml]

slots:
  clairvoyant:
    interface: dbus
    bus: session
    name: com.github.cassidyjames.clairvoyant

apps:
  clairvoyant:
    command: usr/bin/com.github.cassidyjames.clairvoyant
    desktop: usr/share/applications/com.github.cassidyjames.clairvoyant.desktop
    extensions: [gnome]
